#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

set -o vi
source /usr/local/share/chruby/chruby.sh
source /usr/local/share/chruby/auto.sh

# Add local bin file
export PATH=$HOME/bin:$PATH

source "${ZDOTDIR:-$HOME}/.aliases.zsh"

ZSH_THEME_GIT_PROMPT_NOCACHE=true
source ~/.zsh/git-prompt/zshrc.sh
PROMPT='%F{cyan}${_prompt_sorin_pwd} %f$(git_super_status)%(!. %B%F{red}#%f%b.)${editor_info[keymap]} '
RPROMPT=''

chruby 2.1.2

autoload -U bashcompinit
bashcompinit
source ~/.twig/twig-completion.bash
